input_basedir: "."

input:
  - "accommodation"
  - "administration"
  - "amenity"
  - "barrier"
  - "eat-drink"
  - "emergency"
  - "energy"
  - "health"
  - "money"
  - "nature"
  - "outdoor"
  - "religious"
  - "shop"
  - "sports"
  - "tourism"
  - "transport"

output_basedir: "export"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "font"
size_filter: 14

font:
  output_basedir: "font"
