input_basedir: "."

input:
  - "accommodation"
  - "administration"
  - "amenity"
  - "barrier"
  - "eat-drink"
  - "emergency"
  - "energy"
  - "health"
  - "money"
  - "nature"
  - "outdoor"
  - "religious"
  - "shop"
  - "sports"
  - "tourism"
  - "transport"

output_basedir: "export"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "sprite"
retina: true
size_filter: 14

global_style:
  padding: 1
  fill: "#1a1a1a"

  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.3

sprite:
  cols: 12
  outer_padding: 4
  icon_padding: 4
  filename: "icons"
